// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageProto.proto

package com.test.pacman;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.test.pacman.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 inputMsg = 1;</code>
     * @return Whether the inputMsg field is set.
     */
    boolean hasInputMsg();
    /**
     * <code>optional int32 inputMsg = 1;</code>
     * @return The inputMsg.
     */
    int getInputMsg();

    /**
     * <code>repeated int32 CurrentPosition = 2;</code>
     * @return A list containing the currentPosition.
     */
    java.util.List<java.lang.Integer> getCurrentPositionList();
    /**
     * <code>repeated int32 CurrentPosition = 2;</code>
     * @return The count of currentPosition.
     */
    int getCurrentPositionCount();
    /**
     * <code>repeated int32 CurrentPosition = 2;</code>
     * @param index The index of the element to return.
     * @return The currentPosition at the given index.
     */
    int getCurrentPosition(int index);
  }
  /**
   * Protobuf type {@code com.test.pacman.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.test.pacman.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      currentPosition_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              inputMsg_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                currentPosition_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              currentPosition_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                currentPosition_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                currentPosition_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          currentPosition_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.pacman.MessageProto.internal_static_com_test_pacman_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.pacman.MessageProto.internal_static_com_test_pacman_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.pacman.MessageProto.Request.class, com.test.pacman.MessageProto.Request.Builder.class);
    }

    private int bitField0_;
    public static final int INPUTMSG_FIELD_NUMBER = 1;
    private int inputMsg_;
    /**
     * <code>optional int32 inputMsg = 1;</code>
     * @return Whether the inputMsg field is set.
     */
    @java.lang.Override
    public boolean hasInputMsg() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 inputMsg = 1;</code>
     * @return The inputMsg.
     */
    @java.lang.Override
    public int getInputMsg() {
      return inputMsg_;
    }

    public static final int CURRENTPOSITION_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList currentPosition_;
    /**
     * <code>repeated int32 CurrentPosition = 2;</code>
     * @return A list containing the currentPosition.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getCurrentPositionList() {
      return currentPosition_;
    }
    /**
     * <code>repeated int32 CurrentPosition = 2;</code>
     * @return The count of currentPosition.
     */
    public int getCurrentPositionCount() {
      return currentPosition_.size();
    }
    /**
     * <code>repeated int32 CurrentPosition = 2;</code>
     * @param index The index of the element to return.
     * @return The currentPosition at the given index.
     */
    public int getCurrentPosition(int index) {
      return currentPosition_.getInt(index);
    }
    private int currentPositionMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, inputMsg_);
      }
      if (getCurrentPositionList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(currentPositionMemoizedSerializedSize);
      }
      for (int i = 0; i < currentPosition_.size(); i++) {
        output.writeInt32NoTag(currentPosition_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, inputMsg_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < currentPosition_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(currentPosition_.getInt(i));
        }
        size += dataSize;
        if (!getCurrentPositionList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        currentPositionMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.test.pacman.MessageProto.Request)) {
        return super.equals(obj);
      }
      com.test.pacman.MessageProto.Request other = (com.test.pacman.MessageProto.Request) obj;

      if (hasInputMsg() != other.hasInputMsg()) return false;
      if (hasInputMsg()) {
        if (getInputMsg()
            != other.getInputMsg()) return false;
      }
      if (!getCurrentPositionList()
          .equals(other.getCurrentPositionList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasInputMsg()) {
        hash = (37 * hash) + INPUTMSG_FIELD_NUMBER;
        hash = (53 * hash) + getInputMsg();
      }
      if (getCurrentPositionCount() > 0) {
        hash = (37 * hash) + CURRENTPOSITION_FIELD_NUMBER;
        hash = (53 * hash) + getCurrentPositionList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.test.pacman.MessageProto.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.pacman.MessageProto.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.pacman.MessageProto.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.pacman.MessageProto.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.pacman.MessageProto.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.pacman.MessageProto.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.pacman.MessageProto.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.pacman.MessageProto.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.pacman.MessageProto.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.test.pacman.MessageProto.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.pacman.MessageProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.pacman.MessageProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.pacman.MessageProto.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.test.pacman.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.test.pacman.Request)
        com.test.pacman.MessageProto.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.pacman.MessageProto.internal_static_com_test_pacman_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.pacman.MessageProto.internal_static_com_test_pacman_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.pacman.MessageProto.Request.class, com.test.pacman.MessageProto.Request.Builder.class);
      }

      // Construct using com.test.pacman.MessageProto.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        inputMsg_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        currentPosition_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.pacman.MessageProto.internal_static_com_test_pacman_Request_descriptor;
      }

      @java.lang.Override
      public com.test.pacman.MessageProto.Request getDefaultInstanceForType() {
        return com.test.pacman.MessageProto.Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.test.pacman.MessageProto.Request build() {
        com.test.pacman.MessageProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.test.pacman.MessageProto.Request buildPartial() {
        com.test.pacman.MessageProto.Request result = new com.test.pacman.MessageProto.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.inputMsg_ = inputMsg_;
          to_bitField0_ |= 0x00000001;
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          currentPosition_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.currentPosition_ = currentPosition_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.pacman.MessageProto.Request) {
          return mergeFrom((com.test.pacman.MessageProto.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.pacman.MessageProto.Request other) {
        if (other == com.test.pacman.MessageProto.Request.getDefaultInstance()) return this;
        if (other.hasInputMsg()) {
          setInputMsg(other.getInputMsg());
        }
        if (!other.currentPosition_.isEmpty()) {
          if (currentPosition_.isEmpty()) {
            currentPosition_ = other.currentPosition_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureCurrentPositionIsMutable();
            currentPosition_.addAll(other.currentPosition_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.pacman.MessageProto.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.pacman.MessageProto.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int inputMsg_ ;
      /**
       * <code>optional int32 inputMsg = 1;</code>
       * @return Whether the inputMsg field is set.
       */
      @java.lang.Override
      public boolean hasInputMsg() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 inputMsg = 1;</code>
       * @return The inputMsg.
       */
      @java.lang.Override
      public int getInputMsg() {
        return inputMsg_;
      }
      /**
       * <code>optional int32 inputMsg = 1;</code>
       * @param value The inputMsg to set.
       * @return This builder for chaining.
       */
      public Builder setInputMsg(int value) {
        bitField0_ |= 0x00000001;
        inputMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 inputMsg = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInputMsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        inputMsg_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList currentPosition_ = emptyIntList();
      private void ensureCurrentPositionIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          currentPosition_ = mutableCopy(currentPosition_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 CurrentPosition = 2;</code>
       * @return A list containing the currentPosition.
       */
      public java.util.List<java.lang.Integer>
          getCurrentPositionList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(currentPosition_) : currentPosition_;
      }
      /**
       * <code>repeated int32 CurrentPosition = 2;</code>
       * @return The count of currentPosition.
       */
      public int getCurrentPositionCount() {
        return currentPosition_.size();
      }
      /**
       * <code>repeated int32 CurrentPosition = 2;</code>
       * @param index The index of the element to return.
       * @return The currentPosition at the given index.
       */
      public int getCurrentPosition(int index) {
        return currentPosition_.getInt(index);
      }
      /**
       * <code>repeated int32 CurrentPosition = 2;</code>
       * @param index The index to set the value at.
       * @param value The currentPosition to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentPosition(
          int index, int value) {
        ensureCurrentPositionIsMutable();
        currentPosition_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 CurrentPosition = 2;</code>
       * @param value The currentPosition to add.
       * @return This builder for chaining.
       */
      public Builder addCurrentPosition(int value) {
        ensureCurrentPositionIsMutable();
        currentPosition_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 CurrentPosition = 2;</code>
       * @param values The currentPosition to add.
       * @return This builder for chaining.
       */
      public Builder addAllCurrentPosition(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureCurrentPositionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, currentPosition_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 CurrentPosition = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentPosition() {
        currentPosition_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.test.pacman.Request)
    }

    // @@protoc_insertion_point(class_scope:com.test.pacman.Request)
    private static final com.test.pacman.MessageProto.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.pacman.MessageProto.Request();
    }

    public static com.test.pacman.MessageProto.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.test.pacman.MessageProto.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.test.pacman.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 responseMsg = 1;</code>
     * @return Whether the responseMsg field is set.
     */
    boolean hasResponseMsg();
    /**
     * <code>optional int32 responseMsg = 1;</code>
     * @return The responseMsg.
     */
    int getResponseMsg();

    /**
     * <code>repeated int32 PositionMsg = 2;</code>
     * @return A list containing the positionMsg.
     */
    java.util.List<java.lang.Integer> getPositionMsgList();
    /**
     * <code>repeated int32 PositionMsg = 2;</code>
     * @return The count of positionMsg.
     */
    int getPositionMsgCount();
    /**
     * <code>repeated int32 PositionMsg = 2;</code>
     * @param index The index of the element to return.
     * @return The positionMsg at the given index.
     */
    int getPositionMsg(int index);

    /**
     * <code>optional float SpeedMsg = 3;</code>
     * @return Whether the speedMsg field is set.
     */
    boolean hasSpeedMsg();
    /**
     * <code>optional float SpeedMsg = 3;</code>
     * @return The speedMsg.
     */
    float getSpeedMsg();

    /**
     * <code>repeated int32 LevelSizeMsg = 4;</code>
     * @return A list containing the levelSizeMsg.
     */
    java.util.List<java.lang.Integer> getLevelSizeMsgList();
    /**
     * <code>repeated int32 LevelSizeMsg = 4;</code>
     * @return The count of levelSizeMsg.
     */
    int getLevelSizeMsgCount();
    /**
     * <code>repeated int32 LevelSizeMsg = 4;</code>
     * @param index The index of the element to return.
     * @return The levelSizeMsg at the given index.
     */
    int getLevelSizeMsg(int index);

    /**
     * <code>repeated int32 WallMsgX = 5;</code>
     * @return A list containing the wallMsgX.
     */
    java.util.List<java.lang.Integer> getWallMsgXList();
    /**
     * <code>repeated int32 WallMsgX = 5;</code>
     * @return The count of wallMsgX.
     */
    int getWallMsgXCount();
    /**
     * <code>repeated int32 WallMsgX = 5;</code>
     * @param index The index of the element to return.
     * @return The wallMsgX at the given index.
     */
    int getWallMsgX(int index);

    /**
     * <code>repeated int32 WallMsgY = 6;</code>
     * @return A list containing the wallMsgY.
     */
    java.util.List<java.lang.Integer> getWallMsgYList();
    /**
     * <code>repeated int32 WallMsgY = 6;</code>
     * @return The count of wallMsgY.
     */
    int getWallMsgYCount();
    /**
     * <code>repeated int32 WallMsgY = 6;</code>
     * @param index The index of the element to return.
     * @return The wallMsgY at the given index.
     */
    int getWallMsgY(int index);
  }
  /**
   * Protobuf type {@code com.test.pacman.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.test.pacman.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      positionMsg_ = emptyIntList();
      levelSizeMsg_ = emptyIntList();
      wallMsgX_ = emptyIntList();
      wallMsgY_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              responseMsg_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                positionMsg_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              positionMsg_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                positionMsg_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                positionMsg_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 29: {
              bitField0_ |= 0x00000002;
              speedMsg_ = input.readFloat();
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                levelSizeMsg_ = newIntList();
                mutable_bitField0_ |= 0x00000008;
              }
              levelSizeMsg_.addInt(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) != 0) && input.getBytesUntilLimit() > 0) {
                levelSizeMsg_ = newIntList();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                levelSizeMsg_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                wallMsgX_ = newIntList();
                mutable_bitField0_ |= 0x00000010;
              }
              wallMsgX_.addInt(input.readInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) != 0) && input.getBytesUntilLimit() > 0) {
                wallMsgX_ = newIntList();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                wallMsgX_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000020) != 0)) {
                wallMsgY_ = newIntList();
                mutable_bitField0_ |= 0x00000020;
              }
              wallMsgY_.addInt(input.readInt32());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000020) != 0) && input.getBytesUntilLimit() > 0) {
                wallMsgY_ = newIntList();
                mutable_bitField0_ |= 0x00000020;
              }
              while (input.getBytesUntilLimit() > 0) {
                wallMsgY_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          positionMsg_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          levelSizeMsg_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          wallMsgX_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000020) != 0)) {
          wallMsgY_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.pacman.MessageProto.internal_static_com_test_pacman_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.pacman.MessageProto.internal_static_com_test_pacman_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.pacman.MessageProto.Response.class, com.test.pacman.MessageProto.Response.Builder.class);
    }

    private int bitField0_;
    public static final int RESPONSEMSG_FIELD_NUMBER = 1;
    private int responseMsg_;
    /**
     * <code>optional int32 responseMsg = 1;</code>
     * @return Whether the responseMsg field is set.
     */
    @java.lang.Override
    public boolean hasResponseMsg() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 responseMsg = 1;</code>
     * @return The responseMsg.
     */
    @java.lang.Override
    public int getResponseMsg() {
      return responseMsg_;
    }

    public static final int POSITIONMSG_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList positionMsg_;
    /**
     * <code>repeated int32 PositionMsg = 2;</code>
     * @return A list containing the positionMsg.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getPositionMsgList() {
      return positionMsg_;
    }
    /**
     * <code>repeated int32 PositionMsg = 2;</code>
     * @return The count of positionMsg.
     */
    public int getPositionMsgCount() {
      return positionMsg_.size();
    }
    /**
     * <code>repeated int32 PositionMsg = 2;</code>
     * @param index The index of the element to return.
     * @return The positionMsg at the given index.
     */
    public int getPositionMsg(int index) {
      return positionMsg_.getInt(index);
    }
    private int positionMsgMemoizedSerializedSize = -1;

    public static final int SPEEDMSG_FIELD_NUMBER = 3;
    private float speedMsg_;
    /**
     * <code>optional float SpeedMsg = 3;</code>
     * @return Whether the speedMsg field is set.
     */
    @java.lang.Override
    public boolean hasSpeedMsg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional float SpeedMsg = 3;</code>
     * @return The speedMsg.
     */
    @java.lang.Override
    public float getSpeedMsg() {
      return speedMsg_;
    }

    public static final int LEVELSIZEMSG_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.IntList levelSizeMsg_;
    /**
     * <code>repeated int32 LevelSizeMsg = 4;</code>
     * @return A list containing the levelSizeMsg.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getLevelSizeMsgList() {
      return levelSizeMsg_;
    }
    /**
     * <code>repeated int32 LevelSizeMsg = 4;</code>
     * @return The count of levelSizeMsg.
     */
    public int getLevelSizeMsgCount() {
      return levelSizeMsg_.size();
    }
    /**
     * <code>repeated int32 LevelSizeMsg = 4;</code>
     * @param index The index of the element to return.
     * @return The levelSizeMsg at the given index.
     */
    public int getLevelSizeMsg(int index) {
      return levelSizeMsg_.getInt(index);
    }
    private int levelSizeMsgMemoizedSerializedSize = -1;

    public static final int WALLMSGX_FIELD_NUMBER = 5;
    private com.google.protobuf.Internal.IntList wallMsgX_;
    /**
     * <code>repeated int32 WallMsgX = 5;</code>
     * @return A list containing the wallMsgX.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getWallMsgXList() {
      return wallMsgX_;
    }
    /**
     * <code>repeated int32 WallMsgX = 5;</code>
     * @return The count of wallMsgX.
     */
    public int getWallMsgXCount() {
      return wallMsgX_.size();
    }
    /**
     * <code>repeated int32 WallMsgX = 5;</code>
     * @param index The index of the element to return.
     * @return The wallMsgX at the given index.
     */
    public int getWallMsgX(int index) {
      return wallMsgX_.getInt(index);
    }
    private int wallMsgXMemoizedSerializedSize = -1;

    public static final int WALLMSGY_FIELD_NUMBER = 6;
    private com.google.protobuf.Internal.IntList wallMsgY_;
    /**
     * <code>repeated int32 WallMsgY = 6;</code>
     * @return A list containing the wallMsgY.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getWallMsgYList() {
      return wallMsgY_;
    }
    /**
     * <code>repeated int32 WallMsgY = 6;</code>
     * @return The count of wallMsgY.
     */
    public int getWallMsgYCount() {
      return wallMsgY_.size();
    }
    /**
     * <code>repeated int32 WallMsgY = 6;</code>
     * @param index The index of the element to return.
     * @return The wallMsgY at the given index.
     */
    public int getWallMsgY(int index) {
      return wallMsgY_.getInt(index);
    }
    private int wallMsgYMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, responseMsg_);
      }
      if (getPositionMsgList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(positionMsgMemoizedSerializedSize);
      }
      for (int i = 0; i < positionMsg_.size(); i++) {
        output.writeInt32NoTag(positionMsg_.getInt(i));
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeFloat(3, speedMsg_);
      }
      if (getLevelSizeMsgList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(levelSizeMsgMemoizedSerializedSize);
      }
      for (int i = 0; i < levelSizeMsg_.size(); i++) {
        output.writeInt32NoTag(levelSizeMsg_.getInt(i));
      }
      if (getWallMsgXList().size() > 0) {
        output.writeUInt32NoTag(42);
        output.writeUInt32NoTag(wallMsgXMemoizedSerializedSize);
      }
      for (int i = 0; i < wallMsgX_.size(); i++) {
        output.writeInt32NoTag(wallMsgX_.getInt(i));
      }
      if (getWallMsgYList().size() > 0) {
        output.writeUInt32NoTag(50);
        output.writeUInt32NoTag(wallMsgYMemoizedSerializedSize);
      }
      for (int i = 0; i < wallMsgY_.size(); i++) {
        output.writeInt32NoTag(wallMsgY_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, responseMsg_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < positionMsg_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(positionMsg_.getInt(i));
        }
        size += dataSize;
        if (!getPositionMsgList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        positionMsgMemoizedSerializedSize = dataSize;
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, speedMsg_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < levelSizeMsg_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(levelSizeMsg_.getInt(i));
        }
        size += dataSize;
        if (!getLevelSizeMsgList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        levelSizeMsgMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < wallMsgX_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(wallMsgX_.getInt(i));
        }
        size += dataSize;
        if (!getWallMsgXList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        wallMsgXMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < wallMsgY_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(wallMsgY_.getInt(i));
        }
        size += dataSize;
        if (!getWallMsgYList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        wallMsgYMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.test.pacman.MessageProto.Response)) {
        return super.equals(obj);
      }
      com.test.pacman.MessageProto.Response other = (com.test.pacman.MessageProto.Response) obj;

      if (hasResponseMsg() != other.hasResponseMsg()) return false;
      if (hasResponseMsg()) {
        if (getResponseMsg()
            != other.getResponseMsg()) return false;
      }
      if (!getPositionMsgList()
          .equals(other.getPositionMsgList())) return false;
      if (hasSpeedMsg() != other.hasSpeedMsg()) return false;
      if (hasSpeedMsg()) {
        if (java.lang.Float.floatToIntBits(getSpeedMsg())
            != java.lang.Float.floatToIntBits(
                other.getSpeedMsg())) return false;
      }
      if (!getLevelSizeMsgList()
          .equals(other.getLevelSizeMsgList())) return false;
      if (!getWallMsgXList()
          .equals(other.getWallMsgXList())) return false;
      if (!getWallMsgYList()
          .equals(other.getWallMsgYList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResponseMsg()) {
        hash = (37 * hash) + RESPONSEMSG_FIELD_NUMBER;
        hash = (53 * hash) + getResponseMsg();
      }
      if (getPositionMsgCount() > 0) {
        hash = (37 * hash) + POSITIONMSG_FIELD_NUMBER;
        hash = (53 * hash) + getPositionMsgList().hashCode();
      }
      if (hasSpeedMsg()) {
        hash = (37 * hash) + SPEEDMSG_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getSpeedMsg());
      }
      if (getLevelSizeMsgCount() > 0) {
        hash = (37 * hash) + LEVELSIZEMSG_FIELD_NUMBER;
        hash = (53 * hash) + getLevelSizeMsgList().hashCode();
      }
      if (getWallMsgXCount() > 0) {
        hash = (37 * hash) + WALLMSGX_FIELD_NUMBER;
        hash = (53 * hash) + getWallMsgXList().hashCode();
      }
      if (getWallMsgYCount() > 0) {
        hash = (37 * hash) + WALLMSGY_FIELD_NUMBER;
        hash = (53 * hash) + getWallMsgYList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.test.pacman.MessageProto.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.pacman.MessageProto.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.pacman.MessageProto.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.pacman.MessageProto.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.pacman.MessageProto.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.pacman.MessageProto.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.pacman.MessageProto.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.pacman.MessageProto.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.pacman.MessageProto.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.test.pacman.MessageProto.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.pacman.MessageProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.pacman.MessageProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.pacman.MessageProto.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.test.pacman.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.test.pacman.Response)
        com.test.pacman.MessageProto.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.pacman.MessageProto.internal_static_com_test_pacman_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.pacman.MessageProto.internal_static_com_test_pacman_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.pacman.MessageProto.Response.class, com.test.pacman.MessageProto.Response.Builder.class);
      }

      // Construct using com.test.pacman.MessageProto.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseMsg_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        positionMsg_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        speedMsg_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        levelSizeMsg_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        wallMsgX_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000010);
        wallMsgY_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.pacman.MessageProto.internal_static_com_test_pacman_Response_descriptor;
      }

      @java.lang.Override
      public com.test.pacman.MessageProto.Response getDefaultInstanceForType() {
        return com.test.pacman.MessageProto.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.test.pacman.MessageProto.Response build() {
        com.test.pacman.MessageProto.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.test.pacman.MessageProto.Response buildPartial() {
        com.test.pacman.MessageProto.Response result = new com.test.pacman.MessageProto.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.responseMsg_ = responseMsg_;
          to_bitField0_ |= 0x00000001;
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          positionMsg_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.positionMsg_ = positionMsg_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.speedMsg_ = speedMsg_;
          to_bitField0_ |= 0x00000002;
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          levelSizeMsg_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.levelSizeMsg_ = levelSizeMsg_;
        if (((bitField0_ & 0x00000010) != 0)) {
          wallMsgX_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.wallMsgX_ = wallMsgX_;
        if (((bitField0_ & 0x00000020) != 0)) {
          wallMsgY_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.wallMsgY_ = wallMsgY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.pacman.MessageProto.Response) {
          return mergeFrom((com.test.pacman.MessageProto.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.pacman.MessageProto.Response other) {
        if (other == com.test.pacman.MessageProto.Response.getDefaultInstance()) return this;
        if (other.hasResponseMsg()) {
          setResponseMsg(other.getResponseMsg());
        }
        if (!other.positionMsg_.isEmpty()) {
          if (positionMsg_.isEmpty()) {
            positionMsg_ = other.positionMsg_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePositionMsgIsMutable();
            positionMsg_.addAll(other.positionMsg_);
          }
          onChanged();
        }
        if (other.hasSpeedMsg()) {
          setSpeedMsg(other.getSpeedMsg());
        }
        if (!other.levelSizeMsg_.isEmpty()) {
          if (levelSizeMsg_.isEmpty()) {
            levelSizeMsg_ = other.levelSizeMsg_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureLevelSizeMsgIsMutable();
            levelSizeMsg_.addAll(other.levelSizeMsg_);
          }
          onChanged();
        }
        if (!other.wallMsgX_.isEmpty()) {
          if (wallMsgX_.isEmpty()) {
            wallMsgX_ = other.wallMsgX_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureWallMsgXIsMutable();
            wallMsgX_.addAll(other.wallMsgX_);
          }
          onChanged();
        }
        if (!other.wallMsgY_.isEmpty()) {
          if (wallMsgY_.isEmpty()) {
            wallMsgY_ = other.wallMsgY_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureWallMsgYIsMutable();
            wallMsgY_.addAll(other.wallMsgY_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.pacman.MessageProto.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.pacman.MessageProto.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int responseMsg_ ;
      /**
       * <code>optional int32 responseMsg = 1;</code>
       * @return Whether the responseMsg field is set.
       */
      @java.lang.Override
      public boolean hasResponseMsg() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 responseMsg = 1;</code>
       * @return The responseMsg.
       */
      @java.lang.Override
      public int getResponseMsg() {
        return responseMsg_;
      }
      /**
       * <code>optional int32 responseMsg = 1;</code>
       * @param value The responseMsg to set.
       * @return This builder for chaining.
       */
      public Builder setResponseMsg(int value) {
        bitField0_ |= 0x00000001;
        responseMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 responseMsg = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseMsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        responseMsg_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList positionMsg_ = emptyIntList();
      private void ensurePositionMsgIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          positionMsg_ = mutableCopy(positionMsg_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 PositionMsg = 2;</code>
       * @return A list containing the positionMsg.
       */
      public java.util.List<java.lang.Integer>
          getPositionMsgList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(positionMsg_) : positionMsg_;
      }
      /**
       * <code>repeated int32 PositionMsg = 2;</code>
       * @return The count of positionMsg.
       */
      public int getPositionMsgCount() {
        return positionMsg_.size();
      }
      /**
       * <code>repeated int32 PositionMsg = 2;</code>
       * @param index The index of the element to return.
       * @return The positionMsg at the given index.
       */
      public int getPositionMsg(int index) {
        return positionMsg_.getInt(index);
      }
      /**
       * <code>repeated int32 PositionMsg = 2;</code>
       * @param index The index to set the value at.
       * @param value The positionMsg to set.
       * @return This builder for chaining.
       */
      public Builder setPositionMsg(
          int index, int value) {
        ensurePositionMsgIsMutable();
        positionMsg_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 PositionMsg = 2;</code>
       * @param value The positionMsg to add.
       * @return This builder for chaining.
       */
      public Builder addPositionMsg(int value) {
        ensurePositionMsgIsMutable();
        positionMsg_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 PositionMsg = 2;</code>
       * @param values The positionMsg to add.
       * @return This builder for chaining.
       */
      public Builder addAllPositionMsg(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensurePositionMsgIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, positionMsg_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 PositionMsg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPositionMsg() {
        positionMsg_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private float speedMsg_ ;
      /**
       * <code>optional float SpeedMsg = 3;</code>
       * @return Whether the speedMsg field is set.
       */
      @java.lang.Override
      public boolean hasSpeedMsg() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional float SpeedMsg = 3;</code>
       * @return The speedMsg.
       */
      @java.lang.Override
      public float getSpeedMsg() {
        return speedMsg_;
      }
      /**
       * <code>optional float SpeedMsg = 3;</code>
       * @param value The speedMsg to set.
       * @return This builder for chaining.
       */
      public Builder setSpeedMsg(float value) {
        bitField0_ |= 0x00000004;
        speedMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float SpeedMsg = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeedMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        speedMsg_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList levelSizeMsg_ = emptyIntList();
      private void ensureLevelSizeMsgIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          levelSizeMsg_ = mutableCopy(levelSizeMsg_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 LevelSizeMsg = 4;</code>
       * @return A list containing the levelSizeMsg.
       */
      public java.util.List<java.lang.Integer>
          getLevelSizeMsgList() {
        return ((bitField0_ & 0x00000008) != 0) ?
                 java.util.Collections.unmodifiableList(levelSizeMsg_) : levelSizeMsg_;
      }
      /**
       * <code>repeated int32 LevelSizeMsg = 4;</code>
       * @return The count of levelSizeMsg.
       */
      public int getLevelSizeMsgCount() {
        return levelSizeMsg_.size();
      }
      /**
       * <code>repeated int32 LevelSizeMsg = 4;</code>
       * @param index The index of the element to return.
       * @return The levelSizeMsg at the given index.
       */
      public int getLevelSizeMsg(int index) {
        return levelSizeMsg_.getInt(index);
      }
      /**
       * <code>repeated int32 LevelSizeMsg = 4;</code>
       * @param index The index to set the value at.
       * @param value The levelSizeMsg to set.
       * @return This builder for chaining.
       */
      public Builder setLevelSizeMsg(
          int index, int value) {
        ensureLevelSizeMsgIsMutable();
        levelSizeMsg_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 LevelSizeMsg = 4;</code>
       * @param value The levelSizeMsg to add.
       * @return This builder for chaining.
       */
      public Builder addLevelSizeMsg(int value) {
        ensureLevelSizeMsgIsMutable();
        levelSizeMsg_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 LevelSizeMsg = 4;</code>
       * @param values The levelSizeMsg to add.
       * @return This builder for chaining.
       */
      public Builder addAllLevelSizeMsg(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureLevelSizeMsgIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, levelSizeMsg_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 LevelSizeMsg = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLevelSizeMsg() {
        levelSizeMsg_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList wallMsgX_ = emptyIntList();
      private void ensureWallMsgXIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          wallMsgX_ = mutableCopy(wallMsgX_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated int32 WallMsgX = 5;</code>
       * @return A list containing the wallMsgX.
       */
      public java.util.List<java.lang.Integer>
          getWallMsgXList() {
        return ((bitField0_ & 0x00000010) != 0) ?
                 java.util.Collections.unmodifiableList(wallMsgX_) : wallMsgX_;
      }
      /**
       * <code>repeated int32 WallMsgX = 5;</code>
       * @return The count of wallMsgX.
       */
      public int getWallMsgXCount() {
        return wallMsgX_.size();
      }
      /**
       * <code>repeated int32 WallMsgX = 5;</code>
       * @param index The index of the element to return.
       * @return The wallMsgX at the given index.
       */
      public int getWallMsgX(int index) {
        return wallMsgX_.getInt(index);
      }
      /**
       * <code>repeated int32 WallMsgX = 5;</code>
       * @param index The index to set the value at.
       * @param value The wallMsgX to set.
       * @return This builder for chaining.
       */
      public Builder setWallMsgX(
          int index, int value) {
        ensureWallMsgXIsMutable();
        wallMsgX_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 WallMsgX = 5;</code>
       * @param value The wallMsgX to add.
       * @return This builder for chaining.
       */
      public Builder addWallMsgX(int value) {
        ensureWallMsgXIsMutable();
        wallMsgX_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 WallMsgX = 5;</code>
       * @param values The wallMsgX to add.
       * @return This builder for chaining.
       */
      public Builder addAllWallMsgX(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureWallMsgXIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, wallMsgX_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 WallMsgX = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearWallMsgX() {
        wallMsgX_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList wallMsgY_ = emptyIntList();
      private void ensureWallMsgYIsMutable() {
        if (!((bitField0_ & 0x00000020) != 0)) {
          wallMsgY_ = mutableCopy(wallMsgY_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated int32 WallMsgY = 6;</code>
       * @return A list containing the wallMsgY.
       */
      public java.util.List<java.lang.Integer>
          getWallMsgYList() {
        return ((bitField0_ & 0x00000020) != 0) ?
                 java.util.Collections.unmodifiableList(wallMsgY_) : wallMsgY_;
      }
      /**
       * <code>repeated int32 WallMsgY = 6;</code>
       * @return The count of wallMsgY.
       */
      public int getWallMsgYCount() {
        return wallMsgY_.size();
      }
      /**
       * <code>repeated int32 WallMsgY = 6;</code>
       * @param index The index of the element to return.
       * @return The wallMsgY at the given index.
       */
      public int getWallMsgY(int index) {
        return wallMsgY_.getInt(index);
      }
      /**
       * <code>repeated int32 WallMsgY = 6;</code>
       * @param index The index to set the value at.
       * @param value The wallMsgY to set.
       * @return This builder for chaining.
       */
      public Builder setWallMsgY(
          int index, int value) {
        ensureWallMsgYIsMutable();
        wallMsgY_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 WallMsgY = 6;</code>
       * @param value The wallMsgY to add.
       * @return This builder for chaining.
       */
      public Builder addWallMsgY(int value) {
        ensureWallMsgYIsMutable();
        wallMsgY_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 WallMsgY = 6;</code>
       * @param values The wallMsgY to add.
       * @return This builder for chaining.
       */
      public Builder addAllWallMsgY(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureWallMsgYIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, wallMsgY_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 WallMsgY = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearWallMsgY() {
        wallMsgY_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.test.pacman.Response)
    }

    // @@protoc_insertion_point(class_scope:com.test.pacman.Response)
    private static final com.test.pacman.MessageProto.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.pacman.MessageProto.Response();
    }

    public static com.test.pacman.MessageProto.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.test.pacman.MessageProto.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_pacman_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_pacman_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_pacman_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_pacman_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022MessageProto.proto\022\017com.test.pacman\"F\n" +
      "\007Request\022\025\n\010inputMsg\030\001 \001(\005H\000\210\001\001\022\027\n\017Curre" +
      "ntPosition\030\002 \003(\005B\013\n\t_inputMsg\"\247\001\n\010Respon" +
      "se\022\030\n\013responseMsg\030\001 \001(\005H\000\210\001\001\022\023\n\013Position" +
      "Msg\030\002 \003(\005\022\025\n\010SpeedMsg\030\003 \001(\002H\001\210\001\001\022\024\n\014Leve" +
      "lSizeMsg\030\004 \003(\005\022\020\n\010WallMsgX\030\005 \003(\005\022\020\n\010Wall" +
      "MsgY\030\006 \003(\005B\016\n\014_responseMsgB\013\n\t_SpeedMsgb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_test_pacman_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_test_pacman_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_pacman_Request_descriptor,
        new java.lang.String[] { "InputMsg", "CurrentPosition", "InputMsg", });
    internal_static_com_test_pacman_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_test_pacman_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_pacman_Response_descriptor,
        new java.lang.String[] { "ResponseMsg", "PositionMsg", "SpeedMsg", "LevelSizeMsg", "WallMsgX", "WallMsgY", "ResponseMsg", "SpeedMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
